### ISSUE TITLE
PEX Back-end Errors

### ISSUE THREAD

**Issue by JilkOwez** [PEXPlugins/PermissionsEx#2862] opened 2017-07-11 15:42 UTC
Hi, This is my first post on GitHub so bare with me.

I am making a spigot server on Minecraft 1.12. I am encountering some issues with PEX. It is something to do with permissions on the back-end of Java. At first, I thought it was essentials as it said version mismatch but I fixed that and it did nothing. This is the errors that i am getting (picture):

![ws](https://user-images.githubusercontent.com/30081702/28076793-a3b44c82-6657-11e7-8b61-5d01eb77c0a9.PNG)
![dg](https://user-images.githubusercontent.com/30081702/28076794-a3b69e9c-6657-11e7-913b-471563149548.PNG)
![ht](https://user-images.githubusercontent.com/30081702/28076795-a4078848-6657-11e7-8fa3-e0a0897787a2.PNG)

------

When I start my server up, PEX just does not work and does not show prefixes. It just crashes and does not reload or retry. I have cheaked all of my code and I am pretty sure its fine. Code:
```
groups:
  Newcomer:
    options:
     default: true
     rank: 1
     prefix: '[Newcomer] '
    permissions:
     - modifyworld.*
     - essentials.kit
     - essentials.balance
     - essentials.eco
     - essentials.pay
     - essentials.sell
     - essentials.afk
     - essentials.rules
     - essentials.clearinventory
     - essentials.tpa
     - essentials.warp
     - essentials.warp.list
    
   Dotator:
    options:
     default: false
     rank: 2
     prefix: '[&cMember&f] '
    inheritance:
     - Newcomer
    permissions:
     - essentials.keepxp
     - essentials.back.ondeath
     - essentials.home
     - essentials.delhome
     - essentials.fly
     - essentials.home.bed
     - essentials.tpaall
     - essentials.enderchest
     - essentials.heal
      
   Youtuber:
    options:
     default: false
     rank: 3
     prefix: '[&cYoutuber&f] '
    inheritance:
     - Newcomer
     - Dotator
      
   Moderator:
    options:
     default: false
     rank: 10
     prefix: '&d[&1Moderator&d] '
    inheritance:
     - Newcomer
     - Dotator
    permissions:
     - essentials.mute.offline
     - essentials.mute
     - essentials.broadcast
     - essentials.clearinventory.others
     - essentials.kick
     - essentials.kill
     - essentials.kill.force
     - essentials.jails
     - essentials.togglejail
     - holograms.help.*
     - holograms.list.*
     - holograms.near.*
     - holograms.info
     - holograms.readtext
     - holograms.reload
     - essentials.invsee
     - essentials.vanis
     - essentials.home.others
     - essentials.tp.*
     - essentials.warp.*
     
    Admin:
    options:
     default: false
     rank: 11
     prefix: '&d[&aAdmin&d]&f '
    inheritance:
      - Newcomer
      - Dotator
      - Moderator
    permissions:
     - holograms.create
     - holograms.delete
     - holograms.teleport
     - holograms.copy
     - essentials.invsee
     - essentials.invsee.*
     - essentials.enderchest.*
     - essentials.kill
     - essentials.socialspy.*
     - essentials.tempban
     - essentials.jail.allow
     - essentials.vanish.*
     - essentials.chat.*
     - essentials.protect.*
      
   Co-Owner:
    options:
     default: false
     rank: 998
     prefix: '&d[&eCo-CEO&d]&f '
    permissions:
     - '*'
   
  Owner:
    options:
     default: false
     rank: 999
     prefix: '&d[&bCEO&d]&f '
    permissions:
     - '*'
    
schema-version: 1

users:
  3a26d534-f664-4245-99d2-943d43ee5378:
    permissions:
    - '*'
    group:
    - Owner
    options:
      name: raffeey
  slayer_joe:
    group:
    - Co-Owner
```
Thanks in advanced, Jilk Owez

EDIT: Getting code right

**] Edit by Stormbow: added code tags around the permissions.yml file contents. [**

**Comment by Stormbow** [comment] 2017-07-11 20:20
Here are the issues that will need to be corrected:

• There should not be any blank lines in the file.

• I think you misspelled "Donator".

• Many areas of your file have incorrect indentation and all of your groups have `rank:` values backwards.  A `rank: 1` is more powerful than a `rank: 999`.

• Every group _must have_ an `inheritance:` section on Minecraft 1.9+ servers.  (Since you're running 1.12, you should be using PEX 1.23.4 and following [this example](https://pastebin.com/8ZSHxauG) for indentation and formatting.  You don't _need_ to use all of the sections and info in the example, but if you do, the example shows you where it goes.)  Since your "Newcomer" group doesn't inherit from any other group, look at line 19 of the example to give that group an "empty" inheritance section.

• "Co-Owner" should be "CoOwner" because some plugins will not recognize "Co-Owner" as a group on the server; they will consider it to be "Co" or "Co-" and permissions won't be processed correctly.  (You can keep `prefix: '&d[&eCo-CEO&d]&f '`.)

• The permission node `- '*'` should be used with _**extreme**_ caution because it gives anyone who has it the power to delete groups, essentially destroying the server.  It also gives the users in those groups _**every**_ permission node, including many nodes they _do not_ want (but don't know they don't want yet).

----

Once all of the above issues have been addressed, post a new permissions.yml link (from [Pastebin](http://pastebin)) if you have additional problems.

If the above corrections fixed everything you were concerned about, you can close this ticket below.  :-)

**Comment by JilkOwez** [comment] 2017-07-12 07:03
Thank you for the help and support. I will try it tonight! Did not know ranks where like that!

**Comment by Stormbow** [comment] 2017-07-12 07:05
You're welcome.  I'll be here if ya need me after testing. :-)

**Comment by JilkOwez** [comment] 2017-07-12 18:12
Ok, I have found out that it is probably not the permissions.yml file but something else. I have de-bugged everything and used a helpful generator (http://pex.treedb.tk/view.php) and made a new file. It keeps spewing out the same messages.

I'm using v1.23.4 and before I changed anything, it was fine. It may be the config file. Here it is:

{
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: true
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false
}

Thanks in advance, Jilk Owez

**Comment by Stormbow** [comment] 2017-07-12 19:09
That generator creates the file incorrectly.  The `schema-version: 1` line should come before the `users:` section.

You can try deleting the PermissionsEx\config.yml file and PEX will recreate it.  If any change in the file is the cause of the error, letting PEX recreate the file would definitely fix it.

**Comment by JilkOwez** [comment] 2017-07-13 15:36
For some reason, it did not work still. I am currently re-downloading pex to see if it is anything like that.

**Comment by Stormbow** [comment] 2017-07-13 21:39
Alright, let's start at the very beginning.

First, copy your entire startup log to [Pastebin](http://pastebin.com).  That's everything printed to the server console from the moment you start the server until text stops printing to the window and you see a message similar to "Done!".  Leave the link generated in this thread.

Next, copy your permissions.yml file to Pastebin.  Leave that link in this thread also.

**Comment by JilkOwez** [comment] 2017-07-15 13:47
Ok, sorry of the inactivity. Here is the entire logs of my server: https://pastebin.com/MJhfGMrm 

and here is all of my programming: https://pastebin.com/dGcY0ZRV

**Comment by Stormbow** [comment] 2017-07-15 13:53
Try this permissions.yml: https://pastebin.com/R2TM45Kk

**Comment by Stormbow** [comment] 2017-07-22 09:12
No reply in 7 days.  I guess all problems were resolved.

**Closed by Stormbow** 2017-07-22 09:12 UTC
