### ISSUE TITLE
Group inheritance - Prefixes and suffixes

### ISSUE THREAD

**Issue by AfkF24** [PEXPlugins/PermissionsEx#2834] opened 2017-06-18 13:12 UTC
Is there a way to only inherit group permissions and not group prefixes/suffixes as well? 

Here's an example:

```
  Group1:
    options:
      prefix: '[Group1] '
    permissions:
    - perm.permission
  Group2:
    inheritance:
    - Group1
    options:
      suffix: ' [Group2]'
```

If I now assign the group "Group2" to a user, the chat would end up looking like "[Group1] User [Group2]: Message" instead of "User [Group2]: Message" which i initially wanted.

**Comment by Stormbow** [comment] 2017-06-18 13:43
A couple of things to keep in mind when using PEX:

• The display of Prefixes/Suffixes in-game is handled by a chat management plugin; PEX just gives you a place to store that information.

• PEX doesn't allow a group to "inherit" another group's Prefix/Suffix, but a user in multiple groups will display the Prefix/Suffix of the latest group they were added to unless you use `weight:` values.  Take a look at [this example file](https://pastebin.com/8ZSHxauG).  If a user on this server were in the "Member" and "Admin" group, the chat management plugin would display the "Admin" group's prefix _and_ suffix because the "Admin" group has a more powerful `weight:` value— the lower the number, the more powerful the group is.

Does that help?

**Comment by AfkF24** [comment] 2017-06-18 13:57
That's weird since I have the same problem even when using the "weight" system... Could this be EssentialsChat's problem?

**Comment by Stormbow** [comment] 2017-06-18 14:02
It's probably a config issue then.  The `{displayname}` variable in EssentialsChat and EssentialsXChat is actually `prefix+username+suffix`, and would still conform to the "latest group" thing I mentioned, until weights are assigned to the groups.

If you'd like to Pastebin your Essentials\config.yml, your complete permissions.yml, and give me a specific user that's being problematic, I can look through everything to see where the problem is.

**Comment by Stormbow** [comment] 2017-06-18 14:06
Also, it's very important to be specific— are you using "EssentialsChat" or "Essentials**X**Chat"?  The files required for each plugin are different; "Essentials" was discontinued at Minecraft 1.8.0 and "EssentialsX" was the continuation of the "Essentials" plugin, specifically for Spigot servers.

**Comment by AfkF24** [comment] 2017-06-18 14:10
Okay, thanks! Yeah, forgot to specify that I'm ussing EssentialsX, build 472 to be exact.

Pex permissions.yml: https://pastebin.com/QAtBuLWV
EssentialsX config.yml: https://pastebin.com/0hEUDgX6

**Comment by Stormbow** [comment] 2017-06-18 14:26
Ok, looks like the EssentialsXChat hasn't been properly configured.  Take a look at [this excerpt](https://pastebin.com/eHCCcNuY) of my example config.yml file.  There are a few changes you'll need to make to your file.  With this setup, you'll be able to more directly control how your groups' chat is displayed.

Line 666 of your file does the same thing, in a simpler way, and you can keep that method if you prefer.  I expect neither method would function correctly because of the lines that were "ignored" by EssentialsX in the top half of the "excerpt" I linked above.

**Comment by Stormbow** [comment] 2017-06-18 14:37
Many edits in my previous comment.

**Comment by AfkF24** [comment] 2017-06-18 14:42
I've changed the "top section" of my Essentials config.yml values according to your example, but I still have the exact same problem... 

Since I'm pretty new to PEX, I'm trying out the plugin on my test server, so colors aren't a big deal at the moment.

**Comment by Stormbow** [comment] 2017-06-18 14:48
Are you using any other plugins at the moment?  Some plugins, like Multiverse, also have built-in chat management features that can cause some problems.

Can you show me, exactly, what is being displayed in-game?

**Comment by AfkF24** [comment] 2017-06-18 14:50
Using Vault, EssentialsX with EssentialsXChat, PEX, and other plugins that don't affect the chat by any means. I've linked you the picture in my previous comment.

**Comment by Stormbow** [comment] 2017-06-18 14:52
What are the plugins, though?  I'd never have expected a plugin that controls teleporting between worlds to control chat too.  ;-)

**Comment by Stormbow** [comment] 2017-06-18 14:53
You're literally only in one group, as far as PEX and EssentialsX are concerned, so something else is doing the naughty here.

**Comment by AfkF24** [comment] 2017-06-18 14:54
Damn, okay.. Haha

WorldEdit, WorldGuard, ViaVersion, ProtocolLib, AAC, AACAdditionPro, ConditionalCommands, HolographicDisplays, Factions, Vault, EssentialsX, EssentialsXChat, PermissionEx

**Comment by Stormbow** [comment] 2017-06-18 14:56
Check the Factions plugin config.  Is there anything chat related in there?  (I've never used it on my server.)

**Comment by AfkF24** [comment] 2017-06-18 15:00
I've actually just started the server with only EssentialsX, EssentialsXChat, Vault and PEX loaded, and the same issue occurs

**Comment by AfkF24** [comment] 2017-06-18 15:05
http://prntscr.com/fl7ski

**Comment by Stormbow** [comment] 2017-06-18 15:08
I hate to say this— and I've said this less than 5 times in the last 5 years or whatever that I've been the _official_ PEX guru —but after all we've talked about, I have no idea what is causing this problem.

Going back to _at least_ Minecraft 1.6.4, PEX hasn't allowed a user in one group to to "inherit" the prefix/suffix of another group.  (He may not reply here, but @zml2008 is the _programmer_ for PEX and he can confirm or deny this.)

Looking at this issue, from the top, we have one user, in one group, displaying the prefix of one group and the suffix of another, seemingly inherited.  To the best of my knowledge and based on all the years that I've used PEX (which goes back a couple years before I became the _guru_), inheritance is strictly tied to permissions; it can be either global, world-based, or a combination of the two, but never included prefixes or suffixes.

I am, unfortunately, stumped.

**Comment by Stormbow** [comment] 2017-06-18 15:09
The only other thing I can think of is give the group this option:
```
    suffix; ''
```

(That's 2 apostrophes.  That gives the group an "empty" suffix, as shown in my previous file examples.)

**Comment by Stormbow** [comment] 2017-06-18 15:11
> http://prntscr.com/fl7ski

That works, too.  :-)

**Comment by AfkF24** [comment] 2017-06-18 15:14
Believe it or not, I've actually tried to set the suffix to `suffix: ''` , but that displays the suffix from the inherited group again... So "&r" is the only way.

**Comment by Stormbow** [comment] 2017-06-18 15:18
That's also a very non-PEX-like thing.  O_o?

I'm about to say this must be a server host issue; maybe they're giving out some bogus files.  (Your server's startup log could confirm or deny this.  If you want to copy the entire mess, from the moment the server starts, until text stops printing to the console and you see a message similar to "Done!" to Pastebin, I can take a look at that for you too.  **_Many_** server hosts give out the wrong versions of Essentials files because they don't know the difference between "Essentials" and "EssentialsX".)

**Comment by AfkF24** [comment] 2017-06-18 15:21
I'm actually hosting the test server on my PC, locally, so there probably aren't any issues realted to that stuff

**Comment by AfkF24** [comment] 2017-06-18 15:27
Anyways, thank you for your time & assistance! Cheers! :)

**Comment by Stormbow** [comment] 2017-06-18 15:28
You're welcome.

I'm going to leave this open and tag it over to @zml2008 to see if he can give us any additional insight as to what's going on here.

**Comment by zml2008** [comment] 2017-12-24 05:44
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.

**Closed by zml2008** 2017-12-24 05:44 UTC
