### ISSUE TITLE
ERROR PEX

### ISSUE THREAD

**Issue by DG-Owner** [PEXPlugins/PermissionsEx#2847] opened 2017-06-27 07:37 UTC
This is the error what i get
https://pastebin.com/LUAekGW6
minecraft 1.11.2

plugins:

- autobroadcast
- broadcast
- buycraft
- cclearchat
- chatcolor+
- coloredtablist
- coupons
- cratesplus
- enjinMinecraftplugin
- epicrename
- essentials
- essentialschat
- factions
- guishop
- lwc
- massivecore
- mcmmo
- nohoppercraft
- obsidian auctions
- openinv
- permissionsex
- playervaults
- playtime
- pvptimer
- quickban
- randomteleport
- sudo
- trading
- trollcommandsplusplus
- vanish
- vault
- worldedit
- worldguard
-

**Comment by Stormbow** [comment] 2017-06-27 07:43
What version of PEX are you attempting to use?

Are there any other errors in the console when the server starts up?

**Comment by DG-Owner** [comment] 2017-06-27 07:44
the newest

**Comment by Stormbow** [comment] 2017-06-27 07:45
I'm afraid I will need a more complete answer than that.

**Comment by DG-Owner** [comment] 2017-06-27 07:45
ok PermissionsEx v1.23.4

**Comment by Stormbow** [comment] 2017-06-27 07:46
Are there any other errors in the console when the server starts up?

**Comment by DG-Owner** [comment] 2017-06-27 07:46
i will start the server is will see of there are more errors

**Comment by DG-Owner** [comment] 2017-06-27 07:47
https://pastebin.com/fk4qsKay
there are more errors

**Comment by DG-Owner** [comment] 2017-06-27 07:52
do you know how i can fix it

**Comment by Stormbow** [comment] 2017-06-27 07:54
Make sure all of your plugins are for Minecraft 1.11.2 because version incompatibility/mismatch is the cause of most of the errors in your console.  The Sudo plugin, for example, seems to be for Minecraft 1.10 and can't be expected to work on a 1.11.2 server (without testing) and since it's giving an error, it may not be usable on 1.11.2.

You also have a major error (or more) in your PermissionsEx\permissions.yml file, so I'll need to take a look at that to clear those up.  Fixing this may fix the original error you reported, so Sudo may be functional after we fix this.

**Comment by DG-Owner** [comment] 2017-06-27 07:56
but if start the server and use the sudo command it works fine
[permissionsfile](https://pastebin.com/WkFh2LTX)

**Comment by Stormbow** [comment] 2017-06-27 07:56
I can definitely fix the PermissionsEx\permissions.yml file issues.  You may have to remove some incompatible plugins from the server until they're updated by their authors.

**Comment by DG-Owner** [comment] 2017-06-27 07:57
ok what are the plugins that i must remove

**Comment by Stormbow** [comment] 2017-06-27 08:02
♦ line 78 is missing the closing apostrophe for this line:
```
        prefix: '&5&l[Obsidian] &l
```
♦ Lines 19, 20, and 21 all need to be deleted.  Those are not proper multiworld settings.
```
    worlds:
      essentials.fly:
        permissions: []
```
♦ 
Also, be sure you are following [this example](https://pastebin.com/8ZSHxauG) for the layout, indentation, and formatting of your file.  Every group on your server version _must_ have an `inheritance:` section, or PEX will not function correctly.

**Comment by DG-Owner** [comment] 2017-06-27 08:03
ok will
thank you i will see of it fixed

**Comment by DG-Owner** [comment] 2017-06-27 08:05
it fixed

**Comment by Stormbow** [comment] 2017-06-27 08:05
Wait.  There is much more to fix.  That previous message shouldn't have been sent, but this website changed dramatically recently.

**Comment by Stormbow** [comment] 2017-06-27 08:06
Errors in your permissions file:

♦ line 78 is missing the closing apostrophe for this line:
```
        prefix: '&5&l[Obsidian] &l
```
♦ Lines 19, 20, and 21 all need to be deleted.  Those are not proper multiworld settings.
```
    worlds:
      essentials.fly:
        permissions: []
```
♦ Line 28 needs to be deleted.  It's a permission node listing with no permission node in it.
```
    - 
```
♦ Line 63: Avoid using special characters in group names because some badly programmed and very popular plugins will not recognize those names as being real group names on the server.  Change "Co-Owner" to "CoOwner"; you can still use `prefix: '&4&l[Co-Owner] &1&l'` for the group.
```
  Co-Owner:
```

Also, be sure you are following [this example](https://pastebin.com/8ZSHxauG) for the layout, indentation, and formatting of your file.  Every group on your server version _must_ have an `inheritance:` section, or PEX will not function correctly.

**Comment by Stormbow** [comment] 2017-06-27 08:12
Plugin Issues:

♦ mcMMO, LWC, PlayTime, and your versions of the "Essentials" plugins are all outdated.

Since you're using Spigot, you should be using [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/), and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/).

**Comment by Stormbow** [comment] 2017-06-27 08:13
After you get all of those straightened out, reply to this thread if you have any other problems and I'll see if I can get those straightened out too.

**Comment by Stormbow** [comment] 2017-06-28 18:41
Closing the ticket again.  You can still post here.

**Closed by Stormbow** 2017-06-28 18:41 UTC
