### ISSUE TITLE
pex 1.23.1 rank problem spigot 1.8

### ISSUE THREAD

**Issue by benjabvb** [PEXPlugins/PermissionsEx#1901] opened 2015-02-20 12:25 UTC
Hello,

I have a problem on my spigot server with pex with promote and demote.
Whenever i promote or demote an online player it says that the right rank is given to the certain player.
But ingame only the member and admin rank are given to players, other ranks don't seem to work!
So i ranked myself as owner but when i type something in the chat it displays the rank: admin

Pastebin file: http://pastebin.com/QB7CH7AD

**Comment by CullanP** [comment] 2015-02-20 13:02
Try doing /pex promote and then reloading. The 1.8 pex version on bukkit has issues updating groups. I know this because my plugin basically entirely broke. It wouldn't grab the right groups anymore from pex and only reverting back to 1.2.3 fixed my issue. I really want a reply from the dev, if the issue isn't fixed I'm afraid I'm not going to use pex anymore as this is a huge problem. My plugin relies on pex.

**Comment by benjabvb** [comment] 2015-02-20 13:22
yeah the version of pex for 1.7.10 snapshot worked perfectly but it does not support 1.8
(sorry for bad language i'm dutch)

**Comment by iaxedu** [comment] 2015-02-20 14:25
Got the same issue people need to relog after they have received a new group.

**Comment by Stormbow** [comment] 2015-02-20 20:42
I'm not sure what's going on with this, so Zml will have to answer on this one.

**Comment by Whist34** [comment] 2015-02-21 15:42
I posted about what appears to be the same issue on the Bukkit permissionsex/forums:
http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/permissions-help/75638-need-help-with-permission-file/#p3

I am using Spigot 1.8 (Compiled on 2/20/15) and 1.23.1.

UserB (Non-OP)
Guest: No issues
Member: No issues
Admin: Cannot perform bukkit commands such as: "/weather clear" or "/gamemode 1"
Owner: No issues (Owner has the '*' perm and all other <plugin>.* perms that might be needed.

Stormbow recommended I post here because the issues seem to be the same. My post on the permissionex forums has more info about what Stormbow has already looked at.

**Comment by benjabvb** [comment] 2015-02-24 14:19
Close this thread.
I think it was a problem withe the 2 x snapshot version of essentials.
I ran a new server (spigot 1.8) with pex and reinstalled essentials and now everything seem to work fine.

**Comment by iaxedu** [comment] 2015-02-24 19:30
Erm we still have this issue no need to close it. And to add this also does not happen on my test server but only on my active server with over 50K+ people in the permission file.

**Comment by CullanP** [comment] 2015-02-24 23:37
The group issue only happens to me above version 1.2.3, The plugin is broken internally or idk what's wrong with it. But it's definitely not updating correctly. The fact the dev isn't replying is irritating me as I can't go to 1.8 with this issue happening on my prison server, none of the ranks are grabbed correctly above version 1.2.3. Version 1.2.3 and below works perfectly fine.

**Comment by benjabvb** [comment] 2015-02-25 13:04
are you using essentials?
If you do, try to reinstall both pex and essentials it did the job on my server.
Yeah it's very frustrating that they don't reply, because the latest pex brings along some nasty bugs.

**Comment by iaxedu** [comment] 2015-02-25 13:50
Essentials has nothing to do with groups. I already told you that the bug occurs when you have multiple people listed in your permission file.

**Comment by CathalCraft** [comment] 2015-03-16 04:07
@CullanP Just use 1.23. The 1.23.1 is bugged for me too, so I use 1.23 and it works fine.

**Comment by zml2008** [comment] 2015-04-18 01:55
Can you all test with [PEX 1.23.2](https://github.com/PEXPlugins/PermissionsEx/releases/tag/STABLE-1.23.2) and see if your issue is still present?

**Comment by iaxedu** [comment] 2015-04-19 15:46
Issue is still there :(

**Comment by CullanP** [comment] 2015-04-20 01:06
The issue with ranks not fetching correctly is also still there. I'll just say what I know about this issue. The first being that the issue is lying in one of the caching classes (CachingData, CachingGroupData, or CachingUserData) Not sure which, but I assume it's CachingData. Decompiling 1.22.3 and using all of its caching classes fixed the issue for me.

**Comment by zml2008** [comment] 2015-06-21 23:17
The cachingdata changes have been reverted as of 1.22.9 and 1.23.3

**Closed by zml2008** 2015-06-21 23:17 UTC
