### ISSUE TITLE
Compatible Permission Plugin With EssentialsX 

### ISSUE THREAD

**Issue by ZardosCraft** [PEXPlugins/PermissionsEx#2851] opened 2017-07-01 16:34 UTC
(Lol sorry This is my 3rd post of the day) Anyway I can find a permission plugin that works with EssentialsX because PermissionsEX will not work (which is the one everyone is saying to use) so is there any permission plugin that is compatible with EssentialsX. Thanks!

**Comment by Stormbow** [comment] 2017-07-01 17:28
PermissionsEx 1.23.4 is fully functional up to Minecraft 1.12 and works with EssentialsX going back to Minecraft 1.8 (when it was first created for Spigot servers).

**Comment by Stormbow** [comment] 2017-07-01 17:30
If there is some feature of EssentialsX that you're having problems with, you can give me specific details about it and I can tell you how to get it working correctly.

**Comment by ZardosCraft** [comment] 2017-07-01 17:35
@Stormbow Oh well I tried installing PermisionsEX with EssentialsX and it says  "PERMISSIONS MANAGER IS NOT ACCESSIBLE. IS PERMISSIONSEX ENABLED"

**Comment by Stormbow** [comment] 2017-07-01 17:42
That usually means there's an error in the formatting of the permissions.yml file.  A lot of people use _very_ outdated examples when they make their file and end up getting that error.  You can take a look at [this example](https://pastebin.com/8ZSHxauG) for the most up-to-date and file, using all options except multiworld settings.  A multiworld settings example can be found [right here](https://pastebin.com/ieyQU7w8).  All of the info in these examples can be entered into the file either using Notepad ([`Notepad++`](http://notepad-plus-plus.org/) is better) or by using [PEX commands](https://pastebin.com/Kd269wd7).

**Comment by ZardosCraft** [comment] 2017-07-01 17:58
@Stormbow Are you good at this kinda stuff? Could I send you my permissions.yml and could you tell me whats wrong?

**Comment by Stormbow** [comment] 2017-07-01 18:00
I think there have been 5 problems in the last 250,000 posts (including posts from our previous forums) that I've handled that I should have been able to fix, but I couldn't for some reason.  :-)  I'd say I'm pretty good.

Lemme see what ya got and let me know _exactly_ what you're trying to accomplish.  e.g., I want people in GroupNameHere to be able to DoThisActivity.

**Comment by ZardosCraft** [comment] 2017-07-01 20:58
@Stormbow Ok Thanks!
Heres The Link:https://hastebin.com/zevogiyelo.php

**Comment by Stormbow** [comment] 2017-07-01 20:59
Which version of Minecraft are you running?

**Comment by Stormbow** [comment] 2017-07-01 21:05
Test that out on your server, and if you find out that a user/group can't do something specific that you want them to do, let me know which user/group and what they can't do.  Then I'll help you get that fixed too.

**Comment by ZardosCraft** [comment] 2017-07-01 21:21
@Stormbow Ok I just added it and it says Im in the "Owner" group but my Prefix doesnt show up in chat.. (also A command i would like to add is to all groups is /wild)

**Comment by Stormbow** [comment] 2017-07-01 21:38
> Ok I just added it and it says Im in the "Owner" group but my Prefix doesnt show up in chat..

This is actually handled by a "chat management" plugin.

If you're running a Spigot server, you could get [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) and [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) to display those in-game for you.

As for the `/wild` command, is that from the RandomTeleport plugin?

**Comment by ZardosCraft** [comment] 2017-07-01 21:41
@Stormbow its from https://www.spigotmc.org/resources/wilderness-tp.18431/ and ok thanks I already have vault but ill get EssentialsXChat

**Comment by Stormbow** [comment] 2017-07-01 21:43
Cool.  I found the plugin with that command right as you replied.  LOL

To give everyone access to `/wild`, add the node `wild.wildtp` to the group named "Default" and everyone else will inherit the permission.

You can see the other related permission nodes you may want to give to groups on the [Wilderness-TP](https://www.spigotmc.org/resources/wilderness-tp.18431/) page.

**Comment by Stormbow** [comment] 2017-07-01 21:47
Once you have EssentialsXChat installed, follow [this guide](https://pastebin.com/eHCCcNuY) that I wrote to get it setup correctly.

**Comment by ZardosCraft** [comment] 2017-07-01 21:47
@Stormbow ok thanks and also i got two more questions xD 1.If I want to edit the prefixes can i use Like the underlining code and the bold code and stuff? 2.My name is Red also how do i make my name normal and just my rank red

**Comment by ZardosCraft** [comment] 2017-07-01 21:54
@Stormbow Also could you add the /wild in bc i just tried and it all stopped working xD

**Comment by Stormbow** [comment] 2017-07-01 21:55
> `1.` If I want to edit the prefixes can i use like the underlining code and the bold code and stuff?

Yep.  All of the [formatting codes](http://minecraft.gamepedia.com/Formatting_codes) are usable.  Just be sure you use the ampersand `&` instead of the section symbol `§`.

> `2.` My name is Red also how do i make my name normal and just my rank red

You'll do that using the formatting codes I linked above.  Change the colors using the [color codes](http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes) and use `&r` to reset the color back to default after whatever you wanted to be colored is done being colored.  For example, in the permissions.yml file, if you set "Owner" to have `prefix: '&4[Owner]'`, EssentialsXChat will display this in chat when you talk:
```
    [Owner]ZardosCraft: words you typed.
```
The color code `&4` turns the [Owner] prefix red, but we didn't tell EssentialsXChat to reset to the default color, so it remains red for the username and the words they type in chat.

To fix this, we'd use something like this for the `prefix:  '&4[Owner]&r'`.

**Comment by Stormbow** [comment] 2017-07-01 21:56
> Also could you add the /wild in bc i just tried and **it all stopped working** xD

Usually that means something was changed in the file and now the file contains errors.  Show me the complete file again.

**Comment by ZardosCraft** [comment] 2017-07-01 21:59
ok https://pastebin.com/wQXcBiSD

**Comment by ZardosCraft** [comment] 2017-07-01 22:00
and Ik its not lined up but even when i tried lining it up in didn't work

**Comment by Stormbow** [comment] 2017-07-01 22:01
Oh, you didn't add spaces at the beginning of `wild.wildtp`.  Line 19 of your paste, add 4 spaces at the front of the line, and 1 space between the hyphen and the permission node `wild.wildtp`.

You can fix that, easy!  :-)

**Comment by Stormbow** [comment] 2017-07-01 22:01
What didn't work?

**Comment by ZardosCraft** [comment] 2017-07-01 22:02
ohh 4

**Comment by ZardosCraft** [comment] 2017-07-01 22:02
i added 5 xD

**Comment by Stormbow** [comment] 2017-07-01 22:02
That'll do it. :-)

**Comment by ZardosCraft** [comment] 2017-07-01 22:02
And btw does the [Owner] Rank have access to all commands?

**Comment by Stormbow** [comment] 2017-07-01 22:04
> And btw does the [Owner] Rank have access to all commands?

Yes, because of line 109: `- '*'`.  That's called a "global permission node" and gives you _absolutely everything_, even things you don't want.  When you find something you don't want, make the Owner group look like this:
```
    permissions:
    - -something.you.do.not.want
    - '*'
```

**Comment by ZardosCraft** [comment] 2017-07-01 22:04
oh ok

**Comment by ZardosCraft** [comment] 2017-07-01 22:05
and btw i added 4 spaces and it says "PERMISSIONS MANAGER IS NOT ACCESSIBLE. IS PERMISSIONSEX ENABLED"

**Comment by Stormbow** [comment] 2017-07-01 22:05
Be sure to add that one space between the node and hyphen:
```
    - wild.wildtp
```

**Comment by Stormbow** [comment] 2017-07-01 22:06
```
    -wild.wildtp
```
will cause errors.

**Comment by ZardosCraft** [comment] 2017-07-01 22:06
lol i just did it lemme see if it works

**Comment by ZardosCraft** [comment] 2017-07-01 22:07
yep it did

**Comment by ZardosCraft** [comment] 2017-07-01 22:08
but its letting members use /gamemode

**Comment by ZardosCraft** [comment] 2017-07-01 22:08
I didnt put that as there permissions?

**Comment by ZardosCraft** [comment] 2017-07-01 22:08
oh cause im oped maybe?

**Comment by Stormbow** [comment] 2017-07-01 22:09
Yep.  Don't use OP at all.  That's for Vanilla servers which don't use any plugins at all. :-)

**Comment by Stormbow** [comment] 2017-07-01 22:10
Using OP when you use plugins can make you think things are OR are not programmed correctly on the server.

**Comment by ZardosCraft** [comment] 2017-07-01 22:10
so should i deop my self?

**Comment by Stormbow** [comment] 2017-07-01 22:10
Definitely.

**Comment by ZardosCraft** [comment] 2017-07-01 22:11
ok and anyway how did you say to change my name color (not rank) cause i dont want it red xD

**Comment by ZardosCraft** [comment] 2017-07-01 22:12
it was red before i installed permissions and essentials

**Comment by ZardosCraft** [comment] 2017-07-01 22:12
wait i need to add &r

**Comment by Stormbow** [comment] 2017-07-01 22:14
Here are all the parts of the prefix:  [  + the group name + ] + the username + the words they type.

You can change all the [formatting codes](http://minecraft.gamepedia.com/Formatting_codes) and [color codes](http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes) as much as you want in the `prefix:` option for the group.

**Comment by ZardosCraft** [comment] 2017-07-01 22:15
wow Bro You have been the biggest help EVER your so good at plugins I have looked EVERYWHERE for some1 like you...If you wouldnt mind me asking would you like to by [Plugin-Manager] or even Co-Owner if not i totally understand just my server needs someone like you cause we all suck at plugins xD

**Comment by ZardosCraft** [comment] 2017-07-01 22:16
If so ill give u IP

**Comment by Stormbow** [comment] 2017-07-01 22:18
Thanks for the compliment. :-)

I've been working with @zml2008 (the programmer for PermissionsEx) for something like 5 years, so I'm extremely good with PermissionsEx.  I've run a couple servers of my own over the years, too, so I've got some knowledge of the various plugins and how to get them working in PEX.

But...  I don't actually _play_ Minecraft very much at all anymore.  LOL

I appreciate the offer though, and I'm happy to help out with anything permissions-related as needed.  Just post here in the PEX tickets and I'm usually the one to handle them.  (The programming questions and SQL database questions have to be answered by @zml2008.)

**Comment by Stormbow** [comment] 2017-07-01 22:19
I'd love to come see the server though.  Which version of Minecraft are you running?

**Comment by ZardosCraft** [comment] 2017-07-01 22:19
1.11

**Comment by ZardosCraft** [comment] 2017-07-01 22:19
thx

**Comment by Stormbow** [comment] 2017-07-01 22:19
Beautiful.  What's the address?

**Comment by Stormbow** [comment] 2017-07-01 22:19
(1.11.2 is my favorite, at the moment.)

**Comment by ZardosCraft** [comment] 2017-07-01 22:19
167.114.65.207:25616

**Comment by ZardosCraft** [comment] 2017-07-01 22:20
(not my IP i have it hosted)

**Comment by ZardosCraft** [comment] 2017-07-01 22:22
its not a very big server im just trying to get it built and plugins started

**Comment by Stormbow** [comment] 2017-07-01 22:24
You're running Spigot, right?

**Comment by ZardosCraft** [comment] 2017-07-01 22:24
well Spigot and Bukkit

**Comment by ZardosCraft** [comment] 2017-07-01 22:25
(Apex Minecraft Hosting)

**Comment by ZardosCraft** [comment] 2017-07-01 22:25
but mostly bukkit

**Comment by ZardosCraft** [comment] 2017-07-01 22:25
Is it not working? (i think it has to be 1.11 not 1.11.2)

**Comment by Stormbow** [comment] 2017-07-01 22:26
Right, I have to get a 1.11 client.

**Comment by ZardosCraft** [comment] 2017-07-01 22:28
Lol yeah xD

**Comment by ZardosCraft** [comment] 2017-07-01 22:30
is it not working?

**Comment by Stormbow** [comment] 2017-07-01 22:31
I had to help my dad change his password on his Windows 10 computer. heh

I'll be on the server in a moment.

**Comment by ZardosCraft** [comment] 2017-07-01 22:31
Lol ok your good

**Comment by Stormbow** [comment] 2017-07-01 22:55
**EssentialsX Permission Nodes**:

[Part 1](http://wiki.ess3.net/wiki/Command_Reference/Perm) - The 'classic' Essentials permissions that EssentialsX inherited.

[Part 2](https://github.com/drtshock/Essentials/wiki) - Some EssentialsX-specific nodes, added after EssentialsX took over the "Essentials" name.

**Comment by Stormbow** [comment] 2017-07-01 23:18
**EssentialsX Signs Tutorial:** http://wiki.ess3.net/wiki/Sign_Tutorial

**Comment by Stormbow** [comment] 2017-07-01 23:21
which

**Comment by Stormbow** [comment] 2017-07-01 23:55
PEX Debug Mode: https://pastebin.com/vhcWR2yK

**Comment by Stormbow** [comment] 2017-07-02 01:55
Since we resolved the initial issue(s), I'll close this ticket.

(You can still post here if you need help with PEX stuff.)

**Closed by Stormbow** 2017-07-02 01:55 UTC

**Comment by ZardosCraft** [comment] 2017-07-02 19:03
@Stormbow hey again xD I kinda need help...What would be a good kit plugin that works with PEX And EssentialsX? I would use the essentialsX one but you can't set default kits and in my opinion, is kinda hard...Thx xD

**Comment by ZardosCraft** [comment] 2017-07-02 19:06
@Stormbow Also how do I make my text a different color (automatically without typing &a, etc before each sentence) with PEX?

**Comment by Stormbow** [comment] 2017-07-02 19:18
> What would be a good kit plugin that works with PEX And EssentialsX? I would use the essentialsX one but you can't set default kits and in my opinion, is kinda hard...

Actually... You can use EssentialsX to give everyone a special kit the first time they join the server, and it can be some extremely customized stuff with custom name, lore, and enchantments, and you can even give them a server rulebook.  It's definitely _complicated_, but also definitely worth the effort.  And why use a different plugin to do what one of your existing plugins can already do?  Because Essentials/EssentialsX can do such incredibly, phenomenally amazing kits, I've never looked anywhere else for a kit plugin.

> how do I make my text a different color (automatically without typing &a, etc before each sentence) with PEX?

Since this is a chat-related question, it would be handled by your chat plugin— in this case, EssentialsXChat's config.yml file.  Skip down to the EssentialsChat section of the file and put the `&a` color code toward the end of your group-format section.  For example, using [this guide](https://pastebin.com/eHCCcNuY) that contains `Owner: '{DISPLAYNAME}&r: {MESSAGE}'`, we'd change it to `Owner: '{DISPLAYNAME}&r: &a{MESSAGE}'`.

**Comment by Stormbow** [comment] 2017-07-02 19:19
If you want to check out the starter kit I have on my 1.11.2 test server, I can try to get you connected to that.  Remember, there's no builds or content really, just a lot of not-really-configured plugins so I can see the config files and help people out with them.

**Comment by Stormbow** [comment] 2017-07-02 19:21
(I haven't even fully transferred my permissions settings from the previous public version of the server, so a lot of stuff may be very dysfunctional.)

**Comment by ZardosCraft** [comment] 2017-07-02 19:27
ya sure and thx also in the EssintialsX config.yml I changed the warps to where it takes 5 seconds delay and its not working?

**Comment by Stormbow** [comment] 2017-07-02 19:32
You're not OP'd again, are you?  LOL

The TP timer is actually being bypassed by your global wildcard permission node.  (Remember how I told you `- '*'` gives you nodes you don't want?  This is one of those situations.)

From the Essentials Permission Nodes list:
```
essentials.teleport.cooldown.bypass - Bypass the teleport cooldown
essentials.teleport.timer.bypass - Bypass the teleport delay
essentials.teleport.timer.move - Allows user to move while tp timer is counting down
```

1.11.2 server address is 160.3.105.48

**Comment by ZardosCraft** [comment] 2017-07-02 19:35
ohh yeah i forgot xD also when i opned by EssentialsXspawn config it gave me this xD https://pastebin.com/snLvgTMv

**Comment by Stormbow** [comment] 2017-07-02 19:35
Don't open that.  The spawn.yml is the only spawn-related file you may want to look inside.

**Comment by ZardosCraft** [comment] 2017-07-02 19:38
oh ok xD btw i need to be whitelisted on your server

**Comment by Stormbow** [comment] 2017-07-02 19:39
Oh.  Whoops.

ZardosYT added to whitelist.

**Comment by ZardosCraft** [comment] 2017-07-02 19:50
Sorry game crashed xD

**Comment by ZardosCraft** [comment] 2017-07-02 20:08
http://www.minecraftforum.net/forums/support/server-support/server-administration/2599957-how-to-sell-custom-enchanted-items-on-my-server

**Comment by ZardosCraft** [comment] 2017-07-09 23:09
@Stormbow Hi Again, So On Your Test server (Etreon) when your on the server list your has colors and is moving and it looks super cool. How do you do that?

**Comment by ZardosCraft** [comment] 2017-07-09 23:10
also how 2 more things xD 1.How do I set a default kit that can be reused ever 2 hours 2.My buy/sell signs arent working i tried the guide you linked me to but still didnt work

**Comment by ZardosCraft** [comment] 2017-07-10 02:56
@Stormbow nvm i fixed my signs

**Comment by Stormbow** [comment] 2017-07-10 03:22
> Hi Again, So On Your Test server (Etreon) when your on the server list your has colors and is moving and it looks super cool. How do you do that?

The Minecraft Tools website can help you with a [Custom MotD](http://minecraft.tools/en/motd.php).  :-)

> How do I set a default kit that can be reused ever 2 hours 

This takes a few things being setup in the Essentials\config.yml file, and possibly a rulebook written in the Essentials\book.txt file.

```
  # Do we want to give users anything on first join? Set to '' to disable
  # This kit will be given regardless of cost, and permissions.
  #kit: ''
  kit: newbies
```
Then make a kit which can have custom names, lores, enchantments, etc.  Follow the [Essentials Kits Documentation](http://wiki.ess3.net/wiki/Command_Reference/Kits) to make that.  The `delay:` you want to use is 7200, for 2 hours.  (2 hours × 60 minutes × 60 seconds = 7200)  [Item Data Values](http://minecraft.gamepedia.com/Data_values/Item_IDs) are used for the items to hand out, and you can use [Enchantment IDs](http://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments) instead of names (if you want; you'll be using the "java edition" ID— 3rd column number —for a PC server).
```
kitnamehereusinglowercase:
    delay: 7200
    items:
      - 256 1 digspeed:3 name:Dwarf's_Shovel lore:Diggy|Diggy|Hole
      - 257 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
      - 279:780 1 name:&4Damaged Pickaxe lore:A_damaged|diamond_pickaxe.
      - 364 10 name:Beef_Jerky lore:Some_dried_steak_meat.
```
(The `:780` in `279:780` is how damaged the tool/armor was.  _Don't set this too high for the material type or the player gets an item that disappears the second they get it!!_)

**Comment by ZardosCraft** [comment] 2017-07-14 23:29
@Stormbow oh ok thanks! and btw would you happen to know a fix for "<**Owner [Owner]ZardosYT" because i dont want the first owner there it just came out of no where

**Comment by Stormbow** [comment] 2017-07-14 23:44
[These instructions](https://pastebin.com/eHCCcNuY) usually fix it.

**Comment by ZardosCraft** [comment] 2017-07-15 00:22
@Stormbow lol thx <3

**Comment by ZardosCraft** [comment] 2017-07-15 00:25
@Stormbow wait which part would it be in cause im confused xD

**Comment by Stormbow** [comment] 2017-07-15 01:16
It's a short set of instructions.  :-P

**Comment by ZardosCraft** [comment] 2017-07-15 01:48
@Stormbow ik but im confused because i havent changed the code or did anything and it just started happening and it was working before

**Comment by ZardosCraft** [comment] 2017-07-15 01:50
@Stormbow and my "change-displayname:" is true

**Comment by ZardosCraft** [comment] 2017-07-15 01:55
@Stormbow btw sorry for such late reply my computer has been acting up :/

**Comment by ZardosCraft** [comment] 2017-07-15 04:34
@Stormbow ok everythings messing up now..Some people joined and they are Members and they can do commands that are in their config...

**Comment by Stormbow** [comment] 2017-07-15 04:39
> ik but im confused because i havent changed the code or did anything and it just started happening and it was working before

Change what is in your file to match the [instructions/file excerpt](https://pastebin.com/eHCCcNuY).

> they are Members and they can do commands that are in their config...

That's called "working as intended"; they can do what you allowed them to do.  O_o

**Comment by ZardosCraft** [comment] 2017-07-15 14:22
@Stormbow Lol sorry I meant to type they cant use any permissions

**Comment by Stormbow** [comment] 2017-07-15 14:25
Ok, server log and permissions.yml file to Pastebin and tell me exactly who can't do what.

**Comment by ZardosCraft** [comment] 2017-07-15 16:12
ok..
Server Log:https://pastebin.com/K9z9yj4h
Permissions.yml:https://pastebin.com/8nvbAMTV
And all the ranks cant do any command (sethome,kit,etc)

**Comment by Stormbow** [comment] 2017-07-15 19:09
All your Essentials files are from different versions of "EssentialsX".  Download all the Essentials products you want to use from [this page](https://ci.drtshock.net/job/essentialsx/) and upload them to your server.

That 'version mismatch" is why no one can use the Essentials commands.  You haven't given out `essentials.kit` (access to the /kit command) or `essentials.kits.kitnamehere` either, so even if the Essentials versions issue is fixed, no one will have access to any kits.

**Comment by Stormbow** [comment] 2017-07-15 19:12
Oh, and line 94, you have 2 permission nodes on one line.

**Comment by ZardosCraft** [comment] 2017-07-16 17:53
@Stormbow so just delete them?

**Comment by Stormbow** [comment] 2017-07-16 18:03
> so just delete them?

Lines 111, 44, 63, 82: yes.

Line 94, separate them to their own lines.

**Comment by ZardosCraft** [comment] 2017-07-17 14:07
@Stormbow ok i did that but by different versions what do you mean? where would i find the different versions of EssentialsX?

**Comment by Stormbow** [comment] 2017-07-17 17:02
In the simplest terms, your server host gave you the wrong files.

**Comment by ZardosCraft** [comment] 2017-07-17 21:22
@Stormbow oh so where could I find it?

**Comment by Stormbow** [comment] 2017-07-17 21:24
[In the comment I posted 2 days ago](https://github.com/PEXPlugins/PermissionsEx/issues/2851#issuecomment-315555473). :P

**Comment by ZardosCraft** [comment] 2017-07-17 21:34
@Stormbow No not that i meant the different versions of EssentialsX
 (i already deleted and separated the line problem)

**Comment by Stormbow** [comment] 2017-07-17 21:36
Why would anyone want the wrong versions?

The wrong versions are available from your server host.
The correct versions are available in the link I gave you.

;-)

**Comment by ZardosCraft** [comment] 2017-07-17 21:39
@Stormbow Yes I know that but i dont know where to go to delete the wrong versions all i have is EssentialsX nothing else would i just delete that?

**Comment by Stormbow** [comment] 2017-07-17 21:40
OH!  They're in your server's plugins folder.  Basically, get rid of anything with the world "essentials" in it, then download the 'good' files from the link above, and upload them to your server.

**Comment by ZardosCraft** [comment] 2017-07-17 21:43
@Stormbow ok and would that mess up any custom config in my server?

**Comment by Stormbow** [comment] 2017-07-17 21:45
Nah.  You're not deleting the Essentials folder inside your plugins folder, just the .jar files that are causing the version mismatch.

**Comment by ZardosCraft** [comment] 2017-07-17 21:46
@Stormbow ok. I only have 1 EssentialsX folder in my plugins folder... Even tho i have EssentialsX,EssentialsX Chat, and EsentialsX Spawn

**Comment by ZardosCraft** [comment] 2017-07-17 21:47
@Stormbow opps nvm i see what your saying

**Comment by ZardosCraft** [comment] 2017-07-17 21:49
@Stormbow but my server is on 1.11 so will the "Last Successful Build" work?

**Comment by Stormbow** [comment] 2017-07-17 21:50
Yep.  It'll work.

**Comment by ZardosCraft** [comment] 2017-07-17 21:51
ok thanks..And also on my post about my <**Owner thing do i just copy everything you send me from "Raw paste Bin" and replace it with mine?

**Comment by Stormbow** [comment] 2017-07-17 22:00
No, you only change the sections in the instructions.

**Comment by ZardosCraft** [comment] 2017-07-17 22:10
@Stormbow oh well i already did that but it didnt do anything :/

**Comment by Stormbow** [comment] 2017-07-17 22:12
Did you stop the server before making the changes?

Did you save the changes?

**Comment by ZardosCraft** [comment] 2017-07-17 22:41
@Stormbow yes and yes

**Comment by Stormbow** [comment] 2017-07-17 22:42
OK, so what's not working the way you expected it to now?

**Comment by ZardosCraft** [comment] 2017-07-17 22:53
So My When I Type In Chat it says <**Owner [Owner] ZardosYT i dont want the "<**Owner i just want [Owner] ZardosYT.
![weird 2 owner](https://user-images.githubusercontent.com/29764733/28293223-275afc7a-6b21-11e7-870b-a33be2fbfb23.PNG)

**Comment by Stormbow** [comment] 2017-07-17 22:54
That gets customized in the Essentials\config.yml file, about 75% of the way down the file, and you can find it by searching for `group-formats:`.  Change that area of your file to be like [this example](https://pastebin.com/eHCCcNuY).

**Comment by ZardosCraft** [comment] 2017-07-17 22:58
@Stormbow so delete what i haave <{DISPLAYNAME}> {MESSAGE} and paste...
{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

**Comment by Stormbow** [comment] 2017-07-17 22:59
delete what you have and paste:
```
  #format: '[{GROUP}] {DISPLAYNAME} :&r {MESSAGE}'
 
  #group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'
 
  group-formats:
    Guest: '{DISPLAYNAME}&r: {MESSAGE}'
    Member: '{DISPLAYNAME}&r: {MESSAGE}'
    Mod: '{DISPLAYNAME}&r: {MESSAGE}'
    Admin: '{DISPLAYNAME}&r: {MESSAGE}'
    Owner: '{DISPLAYNAME}&r: {MESSAGE}'
```

**Comment by Stormbow** [comment] 2017-07-17 22:59
Obviously, don't delete the entire contents of your file!

**Comment by ZardosCraft** [comment] 2017-07-17 23:13
@Stormbow ok i have more groups than that tho is that ok?

**Comment by ZardosCraft** [comment] 2017-07-17 23:16
didnt fix it :/ heres pastebin:https://pastebin.com/DjuRDaLc

**Comment by Stormbow** [comment] 2017-07-17 23:34
Your Essentials\config.yml file is missing massive, massive amounts of information.

Was that the entire file?

**Comment by ZardosCraft** [comment] 2017-07-17 23:38
im pretty sure...Here i copied and pasted again https://pastebin.com/wDwE6EhL

**Comment by ZardosCraft** [comment] 2017-07-18 01:31
@Stormbow so it only does the <**Owner thing for me..
![2](https://user-images.githubusercontent.com/29764733/28296615-43b885a2-6b37-11e7-8d1f-397a52454223.PNG)

**Comment by ZardosCraft** [comment] 2017-07-18 01:37
@Stormbow ugh also noone is ever able to do commands like my admin cant even do /gamemode :/

**Comment by Stormbow** [comment] 2017-08-04 20:44
I just saw this notification at the top of this website.

We resolved all these issues, didn't we?

**Comment by ZardosCraft** [comment] 2017-08-06 19:20
no sadly we didnt :/ sorry for late response ive been on vacation xD

**Comment by Stormbow** [comment] 2017-08-07 01:35
Are you sure about that?  I joined the server and everything. :P

**Comment by ZardosCraft** [comment] 2017-08-07 22:55
well my thing stills says **Owner and noone can use any commands except me
